num1=float(input('Enter the first number: '))
num2=float(input('Enter the second number: '))
print('addition: ', (num1)+ (num2))
print('Subtraction: ', (num1) - (num2))
print('mutiplication: ',(num1) * (num2))
print('division: ', (num1) / (num2))